### ISSUE TITLE
Error: Cannot resolve file or directory

### ISSUE THREAD

**Issue by iambusybox** [ffalt/xlsx-extract#2]
Hello!

I'm trying to use xlsx-extract on Windows 7

I'e intsall the package with the command:

D:\Business\Projects\Smart>npm install xlsx-extract --msvs_version=2013

The output is the following:

> node-expat@2.3.9 install D:\Business\Projects\Smart\node_modules\xlsx-extract\node_modules\node-expat
> node-gyp rebuild

D:\Business\Projects\Smart\node_modules\xlsx-extract\node_modules\node-expat>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\
\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (rebuild)
  xmlparse.c
  xmltok.c
  xmlrole.c
..\..\..\deps\libexpat\lib\xmlparse.c(1844): warning C4244: 'return' : conversion from '__int64' to 'XML_Index', possible loss of data [D:\Business\Projects\Smart\node_modules\x
lsx-extract\node_modules\node-expat\build\deps\libexpat\expat.vcxproj]
  expat.vcxproj -> D:\Business\Projects\Smart\node_modules\xlsx-extract\node_modules\node-expat\build\Release\\libexpat.lib
  node-expat.cc
..\node-expat.cc(138): warning C4267: 'argument' : conversion from 'size_t' to 'int', possible loss of data [D:\Business\Projects\Smart\node_modules\xlsx-extract\node_modules\no
de-expat\build\node_expat.vcxproj]
     Creating library D:\Business\Projects\Smart\node_modules\xlsx-extract\node_modules\node-expat\build\Release\node_expat.lib and object D:\Business\Projects\Smart\node_module
s\xlsx-extract\node_modules\node-expat\build\Release\node_expat.exp
  Generating code
  Finished generating code
  node_expat.vcxproj -> D:\Business\Projects\Smart\node_modules\xlsx-extract\node_modules\node-expat\build\Release\\node_expat.node
xlsx-extract@0.0.10 node_modules\xlsx-extract
 commander@2.8.1 (graceful-readlink@1.0.1)
 unzip@0.1.11 (setimmediate@1.0.2, match-stream@0.0.2, readable-stream@1.0.33, pullstream@0.4.1, binary@0.3.0, fstream@0.1.31)
 node-expat@2.3.9 (bindings@1.2.1, debug@2.2.0, nan@2.0.8)

So, no errors.

But once I've laucnhed my application I get the error:

D:\Business\Projects\Smart\node_modules\xlsx-extract\node_modules\node-expat\node_modules\bindings\bindings.js:83
        throw e
              ^
Error: Cannot resolve file or directory D:\Business\Projects\Smart\node_modules\xlsx-extract\node_modules\node-expat\build\node_expat.node in D:\Business\Projects\Smart\node_mod
ules\xlsx-extract\node_modules\node-expat\node_modules\bindings
    at D:\Business\Projects\Smart\node_modules\enhanced-require\node_modules\enhanced-resolve\lib\Resolver.js:63:31
    at D:\Business\Projects\Smart\node_modules\enhanced-require\node_modules\enhanced-resolve\lib\Resolver.js:166:15
    at D:\Business\Projects\Smart\node_modules\enhanced-require\node_modules\enhanced-resolve\lib\Resolver.js:59:4
    at D:\Business\Projects\Smart\node_modules\enhanced-require\node_modules\enhanced-resolve\node_modules\tapable\lib\Tapable.js:134:6
    at Tapable.<anonymous> (D:\Business\Projects\Smart\node_modules\enhanced-require\node_modules\enhanced-resolve\lib\DirectoryDefaultFilePlugin.js:16:51)
    at Storage.provide (D:\Business\Projects\Smart\node_modules\enhanced-require\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:52:20)
    at CachedInputFileSystem.stat (D:\Business\Projects\Smart\node_modules\enhanced-require\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:126:20)
    at Tapable.<anonymous> (D:\Business\Projects\Smart\node_modules\enhanced-require\node_modules\enhanced-resolve\lib\DirectoryDefaultFilePlugin.js:15:6)
    at Tapable.applyPluginsParallelBailResult (D:\Business\Projects\Smart\node_modules\enhanced-require\node_modules\enhanced-resolve\node_modules\tapable\lib\Tapable.js:139:14)

    at Tapable.<anonymous> (D:\Business\Projects\Smart\node_modules\enhanced-require\node_modules\enhanced-resolve\lib\Resolver.js:57:8)
    at Tapable.Resolver.forEachBail (D:\Business\Projects\Smart\node_modules\enhanced-require\node_modules\enhanced-resolve\lib\Resolver.js:171:3)
    at Tapable.doResolve (D:\Business\Projects\Smart\node_modules\enhanced-require\node_modules\enhanced-resolve\lib\Resolver.js:56:7)
    at Tapable.resolve (D:\Business\Projects\Smart\node_modules\enhanced-require\node_modules\enhanced-resolve\lib\Resolver.js:41:14)
    at Tapable.resolveSync (D:\Business\Projects\Smart\node_modules\enhanced-require\node_modules\enhanced-resolve\lib\Resolver.js:16:7)
    at ModuleFactory.createSync (D:\Business\Projects\Smart\node_modules\enhanced-require\lib\ModuleFactory.js:50:40)
    at RequireContext.theRequire (D:\Business\Projects\Smart\node_modules\enhanced-require\lib\RequireContext.js:114:40)

Please, advise how to fix that.

Thank you.

**Comment by ffalt** [comment]
I tried with windows some time ago and it worked. maybe there is an issue in combination with the "enhanced-require" -package seen in the call-stack?
please create a simple test.js (including only xlsx-extract), run that and see if that works.
----
    var filename = 'path/to/your/file.xlsx';

    var XLSX = require('xlsx-extract').XLSX;
    new XLSX().extract(filename, {sheet_id:1})
        .on('sheet', function (sheet) {
            console.log('sheet',sheet); 
        })
        .on('error', function (err) {
            console.error('error', err);
        })
        .on('end', function () {
            console.log('it worked');
        });

----
